import axios from "axios";
import ProgressBar from "@badrap/bar-of-progress";
import Cookies from "js-cookie";

export const formServiceBaseURl = "http://localhost:8001/api/";

export const authBaseURL = "http://localhost:9001/api/";

export const userServiceBaseURL = "http://localhost:8000/";

export const setAuthToken = (): void => {
  var token = Cookies.get("token");
  if (token) {
    // If token exists, set it as Authorization header with Bearer token
    axios.defaults.headers.common["Authorization"] = `Bearer ${token}`;
  } else {
    // If no token, remove the Authorization header
    delete axios.defaults.headers.common["Authorization"];
  }
};

export const getDateFromString = (dateString: string) => {
  const date = new Date(dateString);

  const day = String(date.getDate()).padStart(2, "0");
  const month = String(date.getMonth() + 1).padStart(2, "0"); // January is 0!
  const year = date.getFullYear();

  const formattedDate = `${day}-${month}-${year}`;
  return formattedDate;
};

export const progress = new ProgressBar({
  size: 4,
  color: "#0384fc",
  className: "z-50",
  delay: 100,
});

export const clearCookie = () => {
  const cookies = Cookies.get();
  Object.keys(cookies).forEach((cookieName) => {
    Cookies.remove(cookieName);
  });
};

export const districtToBlockMap = [
  {
    district: "BILASPUR",
    blocks: ["GHUMARWIN-I", "GHUMARWIN-II", "JHANDUTTA", "SADAR", "SWARGHAT"],
  },
  {
    district: "CHAMBA",
    blocks: [
      "BANIKHET",
      "BHARMOUR",
      "CHAMBA",
      "CHOWARI",
      "GAROLA",
      "GEHRA",
      "HARDASPURA",
      "KALHEL",
      "KIANI",
      "MEHLA",
      "PANGI",
      "SALOONI",
      "SIHUNTA",
      "SUNDLA",
      "TISSA",
    ],
  },
  {
    district: "HAMIRPUR",
    blocks: ["BHORANJ", "BIJHARI", "GALORE", "HAMIRPUR", "NADAUN", "SUJANPUR"],
  },
  {
    district: "KANGRA",
    blocks: [
      "BAIJNATH",
      "BHAWARNA",
      "CHADHIAR",
      "DADASIBA",
      "DEHRA",
      "DHARAMSALA",
      "FATEHPUR",
      "INDORA",
      "JAWALI",
      "KANGRA",
      "LAMBAGAON",
      "NAGROTA BAGWAN",
      "NAGROTA SURIAN",
      "NURPUR",
      "PALAMPUR",
      "PANCHRUKHI",
      "RAIT",
      "RAJA KA TALAB",
      "RAKKAR",
    ],
  },
  { district: "KINNAUR", blocks: ["KALPA", "NICHAR", "POOH"] },
  {
    district: "KULLU",
    blocks: ["ANNI", "BANJAR", "KULLU/1", "KULLU/2", "NAGGAR", "NIRMAND"],
  },
  {
    district: "LAHUL & SPITI",
    blocks: ["KAZA", "KEYLONG/1", "KEYLONG/2", "UDAIPUR"],
  },
  {
    district: "MANDI",
    blocks: [
      "AUT",
      "BALH",
      "CHACHIOT/1",
      "CHACHIOT/2",
      "CHAUNTRA/1",
      "CHAUNTRA/2",
      "DHARAMPUR/1",
      "DHARAMPUR/2",
      "DRANG/1",
      "DRANG/2",
      "GOPALPUR/1",
      "GOPALPUR/2",
      "KARSOG/1",
      "KARSOG/2",
      "SADAR/1",
      "SADAR/2",
      "SAIGALOO",
      "SERAJ/1",
      "SERAJ/2",
      "SUNDERNAGAR/1",
      "SUNDERNAGAR/2",
    ],
  },
  {
    district: "SHIMLA",
    blocks: [
      "CHAUHARA",
      "CHOPAL",
      "DEHA",
      "DODRAKAWAR",
      "JUBBAL",
      "KASUMPATI",
      "KOTKHAI",
      "KUMARSAIN",
      "KUPVI",
      "MASHOBRA",
      "MATIANA",
      "NANKHARI",
      "NERWA",
      "RAMPUR",
      "RAMPUR/2 AT SARAHAN",
      "RANSAR (JANGLA)",
      "ROHRU",
      "SHIMLA/4",
      "SUNI",
      "THEOG",
      "TIKKAR",
    ],
  },
  {
    district: "SIRMAUR",
    blocks: [
      "BAKRAS",
      "DADAHU",
      "KAFFOTTA",
      "MAJRA",
      "NAHAN",
      "NARAG",
      "NOHRADHAR",
      "PAONTA SAHIB",
      "RAJGARH",
      "SANGRA",
      "SARAHAN",
      "SATAUN",
      "SHILLAI",
      "SURLA",
    ],
  },
  {
    district: "SOLAN",
    blocks: [
      "ARKI",
      "DHARAMPUR",
      "DHUNDAN",
      "KANDAGHAT",
      "KUTHAR",
      "PATTA NEHLOG",
      "NALAGARH",
      "RAMSHAHAR",
    ],
  },
  {
    district: "UNA",
    blocks: ["AMB", "BANGANA", "GAGRET/1", "GAGRET/2", "HAROLI", "UNA"],
  },
];

export const getIndianStatesAndUTs = () => {
  return [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Lakshadweep",
    "Puducherry",
    "Ladakh",
    "Jammu and Kashmir",
  ];
};

export const getSpokeAndHubCenters = () => {
  return [
    "DH Bilaspur",
    "CHC Panjgain",
    "CH Markand",
    "CH Ghumarvin",
    "CHC Harlog",
    "CHC Kuthera",
    "CHC Bharari",
    "CHC Hatwar",
    "CH Berthin",
    "CHC Jandutta",
    "CHC Talai",
    "CH Gandwal",
    "CHC Swarghat",
    "CH Kihar",
    "CH Salooni",
    "CH Bharmour",
    "CHC Holi",
    "CHC Samote",
    "CHC Bathri",
    "CHC Sahoo",
    "CH Tissa",
    "CH Killar",
    "CHC Choori",
    "CH Bhoranj",
    "CH Nadaun",
    "CH Tauni devi",
    "CHC Galore",
    "CH Sujanpur",
    "CH Barsar",
    "PHC Bhota",
    "CHC Bijhari",
    "CH Palampur",
    "CH Nurpur",
    "CH Kangra",
    "CH Baijnath",
    "CH Garli",
    "CH Dehra",
    "CH Bhawarna",
    "CH Dadasiba",
    "CH Fatehpur",
    "CH Rehan",
    "CH Indora",
    "CH Jwalamukhi",
    "CH Chadihar",
    "CH Nagrota Bagwan",
    "CH Shahpur",
    "CH Thural",
    "CHC Khaira",
    "CHC Sullah",
    "CHC Dheera",
    "CHC Rakkar",
    "CHC Pirsaluhi",
    "CHC Kasba Kotla",
    "CHC Rey",
    "CHC Gopalapur",
    "CHC Bir",
    "CHC Nagrota Surian",
    "CHC Kuthera",
    "CHC Baroh",
    "CHC Tiara",
    "PHC Naura",
    "PHC Dhameta",
    "PHC Bharmar",
    "PHC Raja Ka Talab",
    "PHC Panchrukhi",
    "PHC Sarimolag",
    "PHC Kandi",
    "PHC Yol",
    "PHC Masroor",
    "PHC Seun",
    "PHC Charri",
    "PHC Lkhaniyara",
    "RH Reckong Peo",
    "CH MANALI",
    "CHC PATLIKUHAL",
    "PHC NAGGAR",
    "CH Anni",
    "CH Nirmand",
    "CH Tegubehar",
    "CHC Jari",
    "CH Banjar",
    "CH SAINJ",
    "PHC Hansa",
    "PHC Losar",
    "PHC Kibber",
    "PHC Tabo",
    "CH kaza",
    "RH Keylong",
    "PHC Darcha",
    "CH Udaipur",
    "PHC Tholong",
    "CH Bagsaid",
    "CH Gohar",
    "CH Sarkaghat",
    "CHC Bali Chowki",
    "CH Janjehli",
    "CH Karsog",
    "CHC Churag",
    "CH Kotli",
    "CH Ladbharole",
    "CH Padhar",
    "CH Joginder Nagar",
    "ZH Mandi",
    "CH Sunder Nagar",
    "CH Tihara",
    "CH Sandhole",
    "CH Dharmpur",
    "CHC Chirgaon",
    "CHC KOTKHAI",
    "CH Saraswati Nagar",
    "CH Kumarsain",
    "CH Kotgarh",
    "CHC Nankhari",
    "CH Chaupal",
    "CH Nerwa",
    "CHC Kupvi",
    "CHC Maraog",
    "CHC Mashobra",
    "CHC Shoghi",
    "CH Junga",
    "CHC Koti",
    "CHC Dhami",
    "CH Theog",
    "CH Sarahan",
    "CHC Taklech",
    "CHC Dhargaura",
    "CHC Ghanvi",
    "CH Rampur",
    "CH Sunni",
    "CHC Jalog",
    "CH Rohru",
    "DDUZH RH Shimla",
    "CH Poanta Sahib",
    "CH Rajgarh",
    "CH Dadahu",
    "CH Shillai",
    "CH Sarhan",
    "CHC Sangrah",
    "CH Baddi",
    "CH Chail",
    "CH Kunihar",
    "CHC Chandi",
    "CHC Dharampur",
    "CHC Loharghat",
    "CHC Nalagarh",
    "CHC Ramsheher",
    "CHC Syri",
    "PHC Bainj-ki-hatti",
    "PHC Batal",
    "PHC-HWC Chamiana",
    "PHC Chhausha",
    "PHC Dhundhan",
    "PHC Domehar",
    "PHC Ganagughat",
    "PHC Jangeshu",
    "PHC Joghon",
    "PHC Kalibari",
    "PHC Kanair",
    "PHC Nauni",
    "PHC Patta Brewary",
    "PHC Sai",
    "PHC Subathu",
    "RH Una",
    "CH Amb",
    "CH Chintpurni",
    "CHC Dussara",
    "PHC Akrot",
    "PHC Chururu",
    "PHC Dharamshala Mahanta",
    "PHC Shivpur",
    "CH Gagret",
    "CHC Daulatpur",
    "PHC Amlehar",
    "CH Haroli",
    "CHC Bhadsali",
    "CHC Dulehar",
    "CH Bangana",
    "CHC Thanakalan",
    "PHC Sohari Takoli",
  ];
};
